---
title: "Lower and upper bound sets in multi-objective optimization"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lb_ub_set}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
library(knitr)
library(rgl)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "ublb-",
  warning=FALSE, message=FALSE, include = TRUE, 
  out.width = "99%", fig.width = 8, fig.align = "center", fig.asp = 0.62
)

knit_hooks$set(webgl = hook_webgl, rgl = hook_rgl)
```

```{r setup}
library(gMOIP)
rgl::par3d("family" = "serif")
```

Package `gMOIP` has different features for plotting multi-objective models in 2D and 3D. First of all we may plot the non-dominated set. 

```{r ex1LP, webgl = TRUE, fig.width = 0.1}
dat <- genNDSet(keep = TRUE)
ini3D()
plotHull3D(dat, addR3 = F)
plotPoints3D(dat)
finalize3D()
```



```{r}
#' Convert LaTeX to a png file
#'
#' @param tex TeX string. Remember to escape backslash with \\.
#' @param viewPng View the result in the plots window.
#' @param width Width of the png.
#' @param height Height of the png (`width` are ignored).
#' @param dpi Dpi of the png. Not used if `width` or `height` are specified.
#' @param fontsize Front size used in the LaTeX document.
#' @param calcM Estimate 1 em in pixels in the resulting png.
#'
#' @return The filename of the png or a list if `calcM = TRUE`.
#' @export
#'
#' @examples 
#' tex <- "$\\mathbb{R}_{\\geqq}$"
#' toPng(tex, viewPng = TRUE)
#' toPng(tex, fontsize = 20, viewPng = TRUE)
#' toPng(tex, height = 50, fontsize = 10, viewPng = TRUE)
#' toPng(tex, height = 50, fontsize = 50, viewPng = TRUE)
#' tex <- "MMM"
#' toPng(tex, dpi=72, calcM = T)
#' toPng(tex, width = 100, calcM = T)
#' f <- toPng(tex, dpi=300)
#' pngSize(f)
toPng <- function(tex, width = NULL, height = NULL, dpi = 72, viewPng = FALSE, fontsize = 12, 
                  calcM = FALSE, crop = FALSE) {
   texFile <- tempfile(fileext=".tex")
   pdfFile <- gsub("[.]tex", ".pdf", texFile)
   pngFile <- gsub("[.]tex", ".png", texFile)
   writeLines(c(paste0("\\documentclass[class=scrreprt, fontsize = ", fontsize, "pt]{standalone}"),
                "\\usepackage{amsfonts}",
                "\\usepackage{amssymb}",
                "\\begin{document}",
                tex,
                "\\end{document}"),
              texFile)
   system(paste0("pdflatex -shell-escape -output-directory=", tempdir(), " ", texFile))
   if (crop) system(paste("pdfcrop", pdfFile, pdfFile))
   tmp <- pdftools::pdf_pagesize(pdfFile)
   z <- 1
   if (!is.null(width)) z <- dpi/72 * tmp$width/width
   if (!is.null(height)) z <- dpi/72 * tmp$height/height
   dpi <- dpi * 1/z
   if (calcM) em1 <- sizeM(dpi = dpi, fontsize = fontsize)$w
   pdftools::pdf_convert(pdfFile, format = "png", dpi = dpi, antialias = TRUE, filenames = pngFile) 
   if (viewPng) {
      img <- png::readPNG(pngFile)
      grid::grid.newpage()
      grid::grid.raster(img, just = "center", height = 0.2)
   }
   if (calcM) {
     s <- pngSize(pngFile)
     emPng <- s$w/em1
     return(list(png=pngFile, emPx = em1, emLength = emPng, w = s$w, h = s$h))
   }
   return(pngFile)
}


#' Estimate 1 em in pixels in the resulting png.
#'
#' @param ... Arguments parsed on to `toPng`.
#'
#' @return The width and size of the png.
#' @export
#'
#' @examples sizeM(fontsize=30)
sizeM <- function(...) {
  f <- toPng("M", ...)
  return(pngSize(f))
}


#' To size of the png file.
#'
#' @param png Png file name.
#'
#' @return A list with width and height.
#' @export
#'
#' @examples
pngSize <- function(png) {
    img <- png::readPNG(png)
    w <- dim(img)[2]
    h <- dim(img)[1]
    return(list(w=w,h=h))
}


#' Draw boxes, axes and other text outside the data using TeX strings.
#'
#' @param main The main title for the plot.
#' @param sub The subtitle for the plot.
#' @param xlab The axis labels for the plot .
#' @param ylab The axis labels for the plot .
#' @param zlab The axis labels for the plot .
#' @param line The ``line'' of the plot margin to draw the label on.
#' @param ... Additional parameters which are passed to \code{\link{plotMTeX3D}}.
#' 
#' @details The rectangular prism holding the 3D plot has 12 edges.  They are identified
#' using 3 character strings.  The first character (`x', `y', or `z') selects 
#' the direction of the axis.  The next two characters are each `-' or `+',
#' selecting the lower or upper end of one of the other coordinates.  If only
#' one or two characters are given, the remaining characters default to `-'.  
#' For example \code{edge = 'x+'} draws an x-axis at the high level of y and the
#' low level of z.
#' 
#' By default, \code{axes3d} uses the \code{\link{bbox3d}} function to draw the axes.  
#' The labels will move so that they do not obscure the data.  Alternatively,
#' a vector of arguments as described above may be used, in which case
#' fixed axes are drawn using \code{axis3d}.
#'
#' If \code{pos} is a numeric vector of length 3, \code{edge} determines
#' the direction of the axis and the tick marks, and the values of the
#' other two coordinates in \code{pos} determine the position.  See the
#' examples.
#' @return The object IDs of objects added to the scene.
#' @export
#'
#' @examples
#' ini3D()
#' plot3d(1:2,1:2,1:2, xlab = '', ylab = '', zlab = '', type = "n")
#' plotTitleTeX3D(main = "\\LaTeX", sub = "subtitle $\\alpha$", 
#'                xlab = "$x^1_2$", ylab = "$\\beta$", zlab = "$x\\cdot y$")
plotTitleTeX3D <- function (main = NULL, sub = NULL, xlab = NULL, ylab = NULL, 
    zlab = NULL, line = NA, ...) {
    save <- par3d(skipRedraw = TRUE, ignoreExtent = TRUE)
    on.exit(par3d(save))
    result <- numeric(0)
    if (!is.null(main)) {
        aline <- ifelse(is.na(line), 2, line)
        result <- c(result, main = plotMTeX3D(main, "x++", 
            line = aline, ...))
    }
    if (!is.null(sub)) {
        aline <- ifelse(is.na(line), 3, line)
        result <- c(result, sub = plotMTeX3D(sub, "x", line = aline, 
            ...))
    }
    if (!is.null(xlab)) {
        aline <- ifelse(is.na(line), 2, line)
        result <- c(result, xlab = plotMTeX3D(xlab, "x", line = aline, 
            ...))
    }
    if (!is.null(ylab)) {
        aline <- ifelse(is.na(line), 2, line)
        result <- c(result, ylab = plotMTeX3D(ylab, "y", line = aline, 
            ...))
    }
    if (!is.null(zlab)) {
        aline <- ifelse(is.na(line), 2, line)
        result <- c(result, zlab = plotMTeX3D(zlab, "z", line = aline, 
            ...))
    }
    lowlevel(result)
}




#' Plot TeX in the margin
#'
#' @param tex TeX string
#' @param edge The position at which to draw the axis or text. 
#' @param line The ``line'' of the plot margin to draw the label on.
#' @param at The value of a coordinate at which to draw the axis.
#' @param pos  The position at which to draw the axis or text.
#' @param ... 
#'
#' @return The object IDs of objects added to the scene.
#' @export
#'
#' @examples
plotMTeX3D <- function (tex, edge, line = 0, at = NULL, pos = NA, ...) {
  save <- par3d(ignoreExtent = TRUE)
  on.exit(par3d(save))
  ranges <- rgl:::.getRanges()
  edge <- c(strsplit(edge, "")[[1]], "-", "-")[1:3]
  coord <- match(toupper(edge[1]), c("X", "Y", "Z"))
  if (coord == 2) 
    edge[1] <- edge[2]
  else if (coord == 3) 
    edge[1:2] <- edge[2:3]
  range <- ranges[[coord]]
  if (is.null(at)) 
    at <- mean(range)
  newlen <- max(length(tex), length(line), length(at))
  tex <- rep(tex, len = newlen)
  line <- rep(line, len = newlen)
  at <- rep(at, len = newlen)
  if (all(is.na(pos))) {
    pos <- matrix(NA, 3, length(at))
    if (edge[1] == "+") 
       pos[1, ] <- ranges$x[2]
    else pos[1, ] <- ranges$x[1]
    if (edge[2] == "+") 
       pos[2, ] <- ranges$y[2]
    else pos[2, ] <- ranges$y[1]
    if (edge[3] == "+") 
       pos[3, ] <- ranges$z[2]
    else pos[3, ] <- ranges$z[1]
  }
  else pos <- matrix(pos, 3, length(at))
  pos[coord, ] <- at
  ticksize <- 0.05 * (pos[, 1] - c(mean(ranges$x), mean(ranges$y), 
                                  mean(ranges$z)))
  ticksize[coord] <- 0
  plotTeX3D(pos[1, ] + 3 * ticksize[1] * line, 
            pos[2, ] + 3 * ticksize[2] * line, 
            pos[3, ] + 3 * ticksize[3] * line, tex,
            ...)
}



#' Plot TeX at a position. 
#'
#' @param x 
#' @param y 
#' @param z 
#' @param cex Expansion factor
#' @param fixedSize 
#' @param tex TeX string
#' @param size Size of the generated png.
#' @param ... Arguments passed on to `sprites3d`.
#'
#' @return
#' @export
#'
#' @examples
#' tex <- "$\\mathbb{R}_{\\geqq}$"
#' tex <- "\\LaTeX"
#' tex <- "This is a title"
#' ini3D()
#' plot3d(0:2,0:2,0:2)
#' plotTeX3D(0.75,0.75,0.75, "MMM")
#' plotTeX3D(0.5,0.5,0.5, "MMM", cex = 2)
#' plotTeX3D(1,1,1, "This is a title")
#' ini3D(T)
#' plot3d(0:200,0:200,0:200)
#' plotTeX3D(75,75,75, "MMM")
#' plotTeX3D(50,50,50, "\\LaTeX")
#' plotTeX3D(100,100,100, "This is a title")
plotTeX3D <- function (x, y, z, tex, cex = par("cex"), fixedSize = FALSE, size = 480, ...) {
    f <- toPng(tex, width = size, calcM = TRUE, ...)
    # expand png so same width and height
    system(paste0("C:/tools/ImageMagick-7.0.9-Q16/convert ", f$png, 
                  " -background none -gravity center -extent ", max(f$w,f$h), "x", max(f$w,f$h), " ", f$png))
    tmp <- par3d()$bbox 
    radius <- 1/2 * cex * f$emLength * 20/f$emPx * max(c(tmp[2]-tmp[1], tmp[4]-tmp[3],tmp[6]-tmp[5]) * par3d()$scale)
    sprites3d(x, y, z, texture = f$png, 
        textype = "rgba", col = "white", lit = FALSE, 
        radius = radius, fixedSize = fixedSize, ...)
}
```



```{r, webgl = TRUE}
# loadView(v = view)
rgl::mfrow3d(nr = 1, nc = 3, sharedMouse = TRUE)
## Set R^3_>=
ini3D(argsPlot3d = list(xlim = c(-1,100), ylim = c(-1,100), zlim = c(-1,100)))
plotCones3D(c(0,0,0), drawPoint = F, argsPolygon3d = list(alpha=0.8))
plotTitleTeX3D(main = "$\\mathbb{R}_{\\geqq}$", cex = 4, crop = TRUE)
finalize3D()
rgl::next3d()
## Set R^3_>-
ini3D(clear = FALSE, argsPlot3d = list(xlim = c(-1,100), ylim = c(-1,100), zlim = c(-1,100)))
plotCones3D(c(0,0,0), drawPoint = F, argsPolygon3d = list(alpha=0.8))
rgl::spheres3d(0,0,0, radius = 1, alpha = 0.8, col="gray80")
plotTitleTeX3D(main = "$\\mathbb{R}_{\\geq}$", cex = 4, crop = TRUE)
finalize3D()
rgl::next3d()
## Set R^3_>
ini3D(clear = FALSE, argsPlot3d = list(xlim = c(-1,100), ylim = c(-1,100), zlim = c(-1,100)))
plotCones3D(c(0,0,0), drawPoint = F, argsPolygon3d = list(alpha=0.3, color = "red"))
plotTitleTeX3D(main = "$\\mathbb{R}_{>}$", cex = 4, crop = TRUE)
finalize3D()
```


```{r, eval=FALSE}
## conv(ubSet) + R^3_>= with dominance cones
ubSet <- genNDSet(keep = T)
ini3D(F, argsPlot3d = list(xlim = c(min(ubSet$x)-2,max(ubSet$x)+2), ylim = c(min(ubSet$y)-2,max(ubSet$y)+2), zlim = c(min(ubSet$z)-2,max(ubSet$z)+2)))
plotPoints3D(ubSet[ubSet$dom,1:3])
ubSet <- ubSet[!ubSet$dom,1:3]
# convexHull3D(ubSet, classify = T, addR3 = T)
plotHull3D(ubSet[,1:3], addR3 = T, drawPoints = T, drawPolygons = T, argsPlot3d = list(col="blue"), argsPolygon3d = list(color = "red", alpha = 0.5))
plotCones3D(ubSet, argsPolygon3d = list(color = "grey100", alpha = 1), cube = T)
finalize3D()



## conv(ubSet) + R^3_>= with dominance cones
cent <- c(20,20,20)
r <- 15
planeC <- c(cent+r/3)
planeC <- c(planeC, -sum(planeC^2))
ubSet <- genNDSet(100, keep = T, argsSphere = list(center = cent, radius = r, below = F, plane = planeC))
ini3D(T, argsPlot3d = list(xlim = c(min(ubSet$x)-2,max(ubSet$x)+2), ylim = c(min(ubSet$y)-2,max(ubSet$y)+2), zlim = c(min(ubSet$z)-2,max(ubSet$z)+2)))
plotPoints3D(ubSet[ubSet$dom,1:3])
ubSet <- ubSet[!ubSet$dom,1:3]
plotHull3D(ubSet[,1:3], addR3 = T, drawPoints = T, argsPlot3d = list(col="blue"), argsPolygon3d = list(color = "red", alpha = 0.5))
# plotHull3D(ubSet)
plotCones3D(ubSet, argsPolygon3d = list(color = "grey100", alpha = 1), cube = T)
finalize3D()



## dominance cones
ubSet <- genNDSet(1:20, 300)
ini3D(argsPlot3d = list(xlim = c(0,max(ubSet$x)+2), ylim = c(0,max(ubSet$y)+2), zlim = c(0,max(ubSet$z)+2)))
plotCones3D(ubSet, drawPoint = T, argsPolygon3d = list(alpha = 1, color = "red"), cube = T)
plotCones3D(ubSet, drawPoint = T, argsPolygon3d = list(alpha = 1, color = "green"), reverse = T, cube = T)
finalize3D()



# Example in Dachert17
ubSet <- matrix( c(4,0,4, 3,3,1, 2,2,2), ncol = 3, byrow = TRUE)
row.names(ubSet) <- paste0("z", 1:3)
ini3D(argsPlot3d = list(xlim = c(min(ubSet[,1])-10,max(ubSet[,1])+10), ylim = c(min(ubSet[,2])-10,max(ubSet[,2])+10), zlim = c(min(ubSet[,3])-10),max(ubSet[,3])+10))
m <- rgl::par3d()$bbox[c(1,3,5)]
M <- rgl::par3d()$bbox[c(2,4,6)]
augment <- function(idx, a, b, prefix = "") {
  res <- NULL
  for (i in idx) {
    c <- b
    c[i] <- a[i]
    res <- rbind(res,c)
  }
  row.names(res) <- paste0(prefix,idx)
  return(res)
}
zHat <- augment(1:3, M, m)
# iteration 0
U <- matrix(M, ncol = 3, byrow = T)
row.names(U) <- "u0"
N <- NULL
NHat <- rbind(N,zHat)
plotCube3D(m,M, argsPolygon3d = list(alpha = 0.01, color="red"))
plotPoints3D(U, addText = "both", argsPlot3d = list(alpha = 1, col = "blue", size=15), argsText3d = list(col = "red", adj = c(1,1)))
plotPoints3D(NHat, argsPlot3d = list(type="s", col = "green", radius=0.25))
# iteration 1
z <- ubSet[1,1:3]
u0 <- M
U <- augment(1:3, z, u0, "u")
N<- rbind(N, ubSet[1,1:3, drop=F])
plotCone3D(N, drawPoint = F, argsPolygon3d = list(alpha = 1))
plotPoints3D(N, addText = "both", argsPlot3d = list(type="p", col = "red", size = 12, alpha=1, lit = T))
plotPoints3D(U, addText = "both", argsPlot3d = list(type="s", col = "blue", radius=0.25), argsText3d = list(col = "red", adj = c(1,1)))
# iteration 2
z <- ubSet[2,1:3]
u1 <- U[1,]
u3 <- U[3,]
U <- U[2,,drop=F]
U <- rbind(U,augment(1:3, z, u1, "u1"))
U <- rbind(U,augment(1:3, z, u3, "u3"))
N<- rbind(N, ubSet[2,1:3, drop=F])
U <- U[c(-4,-5),]
plotCone3D(N, drawPoint = F, argsPolygon3d = list(alpha = 1))
plotPoints3D(N, addText = "both", argsPlot3d = list(type="s", col = "red", radius = 0.25))
plotPoints3D(U, addText = "both", argsPlot3d = list(type="s", col = "blue", radius=0.25), argsText3d = list(col = "red", adj = c(1,1)))
# iteration 3
z <- ubSet[3,1:3]
u11 <- U[2,]
u12 <- U[3,]
u32 <- U[4,]
U <- U[-c(2:4),]
U <- rbind(U,augment(1:3, z, u11, "u11"))
U <- rbind(U,augment(1:3, z, u12, "u12"))
U <- rbind(U,augment(1:3, z, u32, "u32"))
U <- U[-c(4,6,8,9),]
N<- rbind(N, ubSet[3,1:3, drop=F])
plotCone3D(N, drawPoint = F, argsPolygon3d = list(alpha = 1))
plotPoints3D(N, addText = "both", argsPlot3d = list(type="s", col = "red", radius = 0.25))
plotPoints3D(U, addText = "both", argsPlot3d = list(type="s", col = "blue", radius=0.25), argsText3d = list(col = "red", adj = c(1,1)))
# plotCone3D(U, reverse = T, cube = T, drawPoint = F, argsPolygon3d = list(alpha = 1))
finalize3D()


## Example in Forget20
```

```{r testing, eval=FALSE}
p <- 3
r <- 1
n <- 100
s <- matrix(rnorm(p*n), ncol = n, byrow = TRUE)
x1 <- apply(s, 2, function(x){x * r/sqrt(sum(x^2))})
apply(x1,2, function(x){sqrt(sum(x^2))})
ini3D()
rgl::spheres3d(c(0,0,0), radius=1, color = "grey100", alpha=0.1)
plotPoints3D(t(x1))
finalize3D()
```




